# render.yaml
services:
  - type: web
    name: ryhaven-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python userbot.py"
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: PHONE
        sync: false
      - key: SESSION
        sync: false
